# Site settings
description: A simple blog based on GH server and Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://allenzyoung.github.io" # the base hostname & protocol for your site 

# User settings
username: Allen Z Young
user_description: A learner, a coder, a reader, an idealist.
user_title: 
email: allenzyoungazy@gmail.com
twitter_username: 
github_username:  allenzyoung
gplus_username: allenzyoung97@gmail.com
disqus_username: allzyoung

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
