# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "The Static Blog of A.Z.Y"
description: > # this means to ignore newlines until "email:"
   A simple blog website based on GH server and Jekyll. 

email: allenzyoung97@gmail.com
#blog logo
logo: "/assets/images/1443848642-62.jpg"
# blog cover
cover: "/assets/images/DK.jpg"

name: ' Allen Z Young '
author: 'Allen Z Young'
author_image: "/assets/images/BarackOctSmall.jpg"

paginate:	5

url: "http://allenzyoung.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
disqus: azyoung

# social icons and sharing options
social:
 # - icon:	twitter
 #   url:	https://twitter.com/dirkfabisch
 #   desc: Follow me on twitter
 #   share_url: http://twitter.com/share
 #   share_title: ?text=
 #   share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/allzyoung
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/allenzyoung
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
