title:            A.Z.Young's Static Blog
description:     A static blog built on GitHub Pages and Jekyll.
url:              # Site url.
signoff:          #AllenZYoung.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://allenzyoung.github.io
    external:     true
  - name:         Email
    url:          mailto:allenzyoungazy@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/allenzyoung
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
