# Site settings
description: A simple blog based on GH server and Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lee52.github.io" 
# the base hostname & protocol for your site 

# User settings
username: Lee52
user_description: A learner, a coder, a reader, an idealist.
user_title: 
email: 529508940@qq.com
twitter_username: allzyoung
github_username:  Lee52
gplus_username: 
disqus_username: azyoung

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
